steps:
    #step 1
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
    # #step 2
    - name: 'gcr.io/cloud-builders/docker'
      args: [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/palawan-converter:$REVISION_ID',
        '-t',
        'gcr.io/$PROJECT_ID/palawan-converter:latest',
        '.'
      ]
    #step 3
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/$PROJECT_ID/palawan-converter:$REVISION_ID"]
    - name: 'gcr.io/cloud-builders/docker'
      args: ["push", "gcr.io/$PROJECT_ID/palawan-converter:latest"]
    #step 4
    - name: 'gcr.io/cloud-builders/kubectl'
      args: [
       'set',
       'image',
       'deployment',
       'palawan-converter',
       'palawan-converter=gcr.io/$PROJECT_ID/palawan-converter:$REVISION_ID',
       '--namespace=${_NAMESPACE}'
      ]
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
      - 'NODE_ENV=${_NAMESPACE}'
